##################################################################################
### Copyright (C), 2008-2030, OPPO Mobile Comm Corp., Ltd
### COLOROS_EDIT, All rights reserved.
###
### File: - nativefeatures.mk
### Description:
###     feature used in native or kernel module to decopule oem modification
###     feature name must start with OPLUS_FEATURE_xxxxx
###     close or disable a feature just comment it,do not assign null to the variable
### Version: 1.0
### Date: 2020-03-18
### Author: Liang.Sun
###
### ------------------------------- Revision History: ----------------------------
### <author>                        <date>       <version>   <desc>
### ------------------------------------------------------------------------------
### Liang.Sun@TECH.Build              2020-03-18   1.0         Create this moudle
##################################################################################

# add feature variable like this : OPLUS_FEATURE_xxxxx = true
# this is not allowed like this OPLUS_FEATURE_xxxxx =
# below is the example
#OPLUS_FEATURE_TEST = yes
# comment the variable if you want to disable it

OPLUS_FEATURE_SHUTDOWN_DETECT = yes
OPLUS_FEATURE_PHOENIX = yes
OPLUS_FEATURE_AGINGTEST = yes
OPLUS_FEATURE_FINGERPRINT = yes
OPLUS_FEATURE_FINGERPRINTPAY = yes
OPLUS_FEATURE_FACERECOGNITION = yes
OPLUS_FEATURE_HEALTHINFO = yes
OPLUS_FEATURE_UIFIRST = yes
OPLUS_FEATURE_PROCESS_RECLAIM = yes
OPLUS_FEATURE_FG_IO_OPT = yes
OPLUS_FEATURE_MEMLEAK_DETECT = yes
OPLUS_FEATURE_CORE_CTL = yes
OPLUS_FEATURE_TP_BASIC = yes
OPLUS_FEATURE_TP_BSPFWUPDATE = yes
OPLUS_FEATURE_MULTI_KSWAPD = yes
OPLUS_FEATURE_ZRAM_OPT = yes
OPLUS_FEATURE_SENSOR = yes
OPLUS_FEATURE_SENSOR_ALGORITHM = yes
OPLUS_FEATURE_SENSOR_NOT_SUPPORT_CAMERA_PROTECT = yes
OPLUS_FEATURE_EXFAT_SUPPORT = yes
OPLUS_FEATURE_SDCARDFS_SUPPORT = yes
OPLUS_FEATURE_MULTI_FREEAREA = yes
OPLUS_FEATURE_VIRTUAL_RESERVE_MEMORY = yes
OPLUS_FEATURE_STORAGE_TOOL = yes
OPLUS_FEATURE_NEW_FTMFLASHLIGHT_NODE = yes
OPLUS_FEATURE_CAMERA_COMMON = yes
OPLUS_FEATURE_WIFI_DATASTALL = yes
OPLUS_FEATURE_WIFI_MTUDETECT = yes
OPLUS_FEATURE_WIFI_SLA =yes
OPLUS_FEATURE_WIFI_GBK = yes
OPLUS_FEATURE_WIFI_DUALSTA = yes
OPLUS_FEATURE_WIFI_OSHARE = yes
OPLUS_FEATURE_WIFI_SUPPLICANTHIDL = yes
OPLUS_FEATURE_WIFI_SMART_BW = yes
OPLUS_FEATURE_WIFI_LIMMITBGSPEED =yes
OPLUS_FEATURE_BT_INTEROPLIST = yes
OPLUS_FEATURE_BT_FW_OVERRIDE_MTK = yes
OPLUS_FEATURE_ATLAS = yes
OPLUS_FEATURE_AUDIO_FTM = yes
OPLUS_FEATURE_AUDIOSERVER_DEBUG = yes
OPLUS_FEATURE_VIP_RECORD = yes
OPLUS_FEATURE_PA_DUMMY = true
OPLUS_FEATURE_SMARTVOL = yes
OPLUS_FEATURE_VOIP_ENHANCE = yes
OPLUS_FEATURE_GAMEVOICEOPTIMIZE = yes
OPLUS_FEATURE_KTV = true
OPLUS_FEATURE_LVIMFS_SUPPORT = yes
OPLUS_FEATURE_PLAYBACKCAPTURE = yes
OPLUS_FEATURE_GAME_MUTE = yes
OPLUS_FEATURE_VOICE_CHANGER = yes
OPLUS_FEATURE_VIBRING_SYNC = true
OPLUS_FEATURE_INPUTCHANNEL_CHOICE = yes
OPLUS_FEATURE_AUDIOVOICE_SCENCE = true
OPLUS_FEATURE_DOLBY = true
OPLUS_FEATURE_DIRAC = true
OPLUS_FEATURE_OPERATOR_RINGTONE = yes
OPLUS_FEATURE_CAMERASOUND_FORCE = yes
OPLUS_FEATURE_FORBID_RECORD = yes
OPLUS_FEATURE_SPEAKER_MUTE = true
OPLUS_FEATURE_SSR = yes
OPLUS_FEATURE_AUDIO_LOWLATENCY = true
OPLUS_FEATURE_GAME_AUDIO_EFFECTS = true
OPLUS_FEATURE_CUSTOM_SCENE = yes
OPLUS_FEATURE_MULTISCENE_RECORD = yes
OPLUS_FEATURE_OPLUS_AVENHANCEMENT = yes
OPLUS_FEATURE_APE_DECODER = yes
OPLUS_FEATURE_VIDEO_TITLE = yes
OPLUS_FEATURE_MP3_RECORDER = yes
OPLUS_FEATURE_FFMPEG_INTEGRATION = yes
OPLUS_FEATURE_FEEDBACK_INFO = yes
OPLUS_FEATURE_IMAGE_PROCESSING = yes
OPLUS_FEATURE_AUDIOBITRATE = yes
OPLUS_FEATURE_ZEN_MODE = yes
OPLUS_FEATURE_ONSCREENFINGERPRINT = yes
OPLUS_FEATURE_DC = yes
OPLUS_FEATURE_AOD = yes
OPLUS_FEATURE_DRE = yes
OPLUS_FEATURE_OSC = yes
OPLUS_FEATURE_AUTOBRIGHTNESS = yes
OPLUS_FEATURE_GPU_MINIDUMP = yes
OPLUS_FEATURE_SCREENSHOT = yes
OPLUS_FEATURE_GIFT = yes
OPLUS_FEATURE_OSIE = yes
OPLUS_FEATURE_VPP = yes
OPLUS_FEATURE_AI_FRAMERATE = yes
OPLUS_FEATURE_GAME_OIFACE = yes
OPLUS_FEATURE_PLATFORM_MTK = yes
OPLUS_FEATURE_FONT_FLIP = yes
OPLUS_FEATURE_MOTION_INTERCEPT = yes
OPLUS_FEATURE_LINKERCONFIG_CUSTOM = yes
OPLUS_FEATURE_RESOURCES_COMPILE = yes
OPLUS_FEATURE_DARKMODE = yes
OPLUS_FEATURE_DUMP_SENSOR = yes
OPLUS_FEATURE_GAMEECO_COOLEFFECT = yes
OPLUS_FEATURE_PLATFORM = MTK
OPLUS_FEATURE_PERFORMANCE = yes
OPLUS_FEATURE_QIHOO_HOTFIX = yes
OPLUS_FEATURE_ENGINEERTOOLS = true
OPLUS_FEATURE_SELINUX_CONTROL_LOG = true
OPLUS_FEATURE_SELINUX_DEBUG_BUILD = true
OPLUS_FEATURE_SELINUX_CONTEXTS = true
OPLUS_FEATURE_DYNAMIC_KEYMAP = yes
OPLUS_FEATURE_DROP_STATUSBAR = yes
OPLUS_FEATURE_GESTURE_SCREENSHOT = yes
OPLUS_FEATURE_STORAGE = yes
OPLUS_FEATURE_STORAGE_MOUNT = yes
OPLUS_FEATURE_STORAGE_RESIZE = yes
OPLUS_FEATURE_STORAGE_TRIM = yes
OPLUS_FEATURE_STORAGE_FBE = yes
OPLUS_FEATURE_STORAGE_MTP = yes
OPLUS_FEATURE_STORAGE_RESERVEPARTITION = yes
OPLUS_FEATURE_STORAGE_USB = yes
OPLUS_FEATURE_STORAGE_CUSTOMIZE_PARTITION = yes
OPLUS_FEATURE_STORAGE_FDE = yes
OPLUS_FEATURE_STORAGE_AUTOMATIC_TIMING = yes
OPLUS_FEATURE_RECOVERY_BUILD = yes
OPLUS_FEATURE_RECOVERY_BOOT = yes
OPLUS_FEATURE_RECOVERY_UI = yes
OPLUS_FEATURE_RECOVERY_RESET = yes
OPLUS_FEATURE_OTAPACKAGE_BUILD = yes
OPLUS_FEATURE_OTAPACKAGE_UPDATER = yes
OPLUS_FEATURE_OTAPACKAGE_SCRIPT = yes
OPLUS_FEATURE_BOOTANIMATION = yes
OPLUS_FEATURE_SECURE_GUARD = yes
OPLUS_FEATURE_SECURE_ROOTGUARD = yes
OPLUS_FEATURE_SECURE_MOUNTGUARD = yes
OPLUS_FEATURE_SECURE_EXECGUARD = yes
OPLUS_FEATURE_SECURE_KEVENTUPLOAD = yes
OPLUS_FEATURE_SECURE_KEYINTERFACESGUARD = yes
OPLUS_FEATURE_ENGINEERING_FILEACCESS = yes
OPLUS_FEATURE_ORMS = yes
OPLUS_FEATURE_MAINLINE = yes
OPLUS_FEATURE_CLOUD_COMPILE = yes
OPLUS_FEATURE_PMS_EXCEPTION_FIX = true
OPLUS_FEATURE_PMS_BOOT_TIME_OPT = true