#ifdef OPLUS_FEATURE_HEALTHINFO
obj-$(CONFIG_OPPO_HEALTHINFO)  +=  oppo_cpuload.o
obj-$(CONFIG_OPPO_JANK_INFO)  +=  oppo_jank_monitor.o
#endif /* OPLUS_FEATURE_HEALTHINFO */
obj-$(CONFIG_FG_TASK_UID)  +=  fg_uid/