#for AWINIC AW87XXX Smart K PA
obj-$(CONFIG_SND_SOC_AW87XXX_2_X_0) += aw87xxx_2_x_0.o  aw87xxx_device_2_x_0.o  aw87xxx_monitor_2_x_0.o  aw87xxx_bin_parse_2_x_0.o  aw87xxx_dsp_2_x_0.o  aw87xxx_acf_bin_2_x_0.o
