#ifdef VENDOR_EDIT
#obj-$(CONFIG_OPPO_CRITICALLOG)	+=  oppo_criticallog.o
#Xiaoshan.Huang
#obj-$(CONFIG_OPPO_CRITICALLOG)   +=  oppo_criticallog.o
#endif /* VENDOR_EDIT */

#ifdef VENDOR_EDIT
#obj-$(CONFIG_OPPO_CRITICALLOG)   +=  oppo_criticallog.o
obj-y  +=  oppo_criticallog.o criticallog_class.o
#endif /* VENDOR_EDIT */
